backend:
  name: github
  repo: yourname/my-shop   # ğŸ‘‰ ì—¬ê¸°ì— ìì‹ ì˜ GitHub ì €ì¥ì†Œ ê²½ë¡œ ì…ë ¥
  branch: main

media_folder: "image"   # ì´ë¯¸ì§€ ì €ì¥ ìœ„ì¹˜
public_folder: "/image

collections:
  - name: "products"
    label: "ìƒí’ˆ ëª©ë¡"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "ìƒí’ˆëª…", name: "title", widget: "string" }
      - { label: "ê°€ê²©", name: "price", widget: "number" }
      - { label: "ì„¤ëª…", name: "description", widget: "text" }
      - { label: "ì´ë¯¸ì§€", name: "image", widget: "image" }
